on:
  push:
    tag:
      - 'v*'

name: release

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RMD_PATH: analysis/paper/paper.Rmd
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install EnergyPlus
        shell: Rscript {0}
        run: |
          if (!eplusr::is_avail_eplus(9.4)) eplusr::install_eplus(9.4)

      - name: Run targets pipeline
        run: targets::tar_make()
        shell: Rscript {0}
        continue-on-error: true

      - name: Retrieve Rmarkdown file
        shell: Rscript {0}
        run: |
          f <- targets::tar_read(paper)
          html <- grep(".html", f, fixed = TRUE, value = TRUE)
          pdf <- grep(".pdf", f, fixed = TRUE, value = TRUE)
          write(c(html, pdf), "results.txt")

      - name: Set RMarkdown output path
        id: rmd
        run: |
          echo "::set-output name=build_dir::$(Rscript -e 'cat(dirname(targets::tar_read(paper))[1])'"
          echo "::set-output name=html_path::$(cat results.txt | grep .html)"
          echo "::set-output name=pdf_path::$(cat results.txt  | grep .pdf)"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create HTML Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{steps.rmd.outputs.html_path}}
          body: ${{steps.github_release.outputs.changelog}}
          overwrite: true
          file_glob: true

      - name: Create PDF Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{steps.rmd.outputs.pdf_path}}
          body: ${{steps.github_release.outputs.changelog}}
          overwrite: true
          file_glob: true
